### PR TITLE
do not evict pods when using Karpenter as autoscale tool

### PR DESCRIPTION
**Pull request by ron-benaim**
https://github.com/env0/agent-helm-chart/issues/2

### CODE REVIEW

**Comment by avnerenv0** [comment]
closing as this was merged elsewhere and the new code now exists in the latest released version.

**Comment by ron-benaim-af** [comment]
Hi @avnerenv0 
Karpenter changed the annotation in recent versions. its now called   karpenter.sh/do-not-disrupt: "true"
https://karpenter.sh/docs/concepts/disruption/#pod-level-controls

Can you fix that in newer chart version?

**Comment by avnerenv0** [comment]
Hi @ron-benaim-af , we can do that, would it make sense to keep both annotations in order to keep support for older versions of Karpenter? 

Thanks

**Comment by ron-benaim-af** [comment]
> Hi @ron-benaim-af , we can do that, would it make sense to keep both annotations in order to keep support for older versions of Karpenter?
> 
> Thanks

Yes, it would be great 🙏

**Comment by ron-benaim-af** [comment]
@avnerenv0 I see now that in latest charts you have added the option to send annotations via values file (.Values.podAdditionalAnnotations)
I think its actually best **not** to add those (like my request) as hardcoded annotations, and let the user enter whats needed.

Or the middle ground of configuring all those annotations (of cluster auto scaler and Karpenter) in the default Values file and keep the scaled-job.yaml without any hardcoded annotations.

**Pull request closed without merging**
